### ISSUE TITLE
Environment.CurrentDirectory

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Legally-Distinct-Missile#17]
Were there any changes how `Environment.CurrentDirectory` gets set?
RocketMod used to set it to the Rocket folder

**Comment by SDGNelson** [comment]
I don't believe so (not on my end). Perhaps it was one of the commits after the release of the final Rocket version? (e.g. your removal of Rocket's console IO was after that) Vanilla Unturned does not set the working directory either. The only working directory related thing that comes to mind is that the Windows .bat scripts expand the script path so that they can be called from anywhere.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
