### ISSUE TITLE
There should be a code cleaning here

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Legally-Distinct-Missile#48]
https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/blob/3e8f5e4919a806911c410eaad7d4d8db8a214e39/Rocket.Unturned/Serialisation/UnturnedSettings.cs

this code is no longer used:
`[XmlElement("RocketModObservatory")]
        public RocketModObservatorySettings RocketModObservatory = new RocketModObservatorySettings();`

**Comment by Sl4vP0weR** [comment]
Sorry, but this is outside the scope of the project. The goal here is only to maintain backwards compatibility with Unturned. If you are interested in implementing it would be relatively straightforward to make the /A custom command. Less so the /Z command because the number of zombies is constant.

_Originally posted by @SDGNelson in https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/issues/42#issuecomment-867117766_

**Comment by SDGNelson** [comment]
Thanks @Sl4vP0weR is correct. That was kept when first tidying things up for this repository because other plugins may have been using it.
